import cv2
image = cv2.imread('Photo.jpeg')
#image=cv2.resize(image,(x,y))
cv2.imshow('Original', image)
cv2.waitKey(0)
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", gray_image)
cv2.waitKey(0)
inverted_image =cv2.bitwise_not(gray_image)
cv2.imshow("Negative", inverted_image)
cv2.waitKey(0)
blurred = cv2.GaussianBlur(inverted_image, (21, 21), 0)
cv2.imshow("Blur", blurred)
cv2.waitKey()
inverted_blurred =cv2.bitwise_not(blurred)
pencil_sketch = cv2.divide(gray_image, inverted_blurred, scale=256.0)
cv2.imshow("Sketch", pencil_sketch)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow("original image", image)
cv2.imshow("pencil sketch", pencil_sketch)
cv2.waitKey(0)
